package com.steve.zap;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.text.InputType; import android.view.*; import android.widget.*; import org.json.*; import java.io.*; import java.net.*; import java.util.concurrent.*;

public class MainActivity extends Activity {
  LinearLayout content; EditText phone,name,pin,target; TextView status; String token=""; String userId="";
  String API="https://YOUR-ZAP-RENDER-URL.onrender.com"; ExecutorService ex=Executors.newSingleThreadExecutor();
  public void onCreate(Bundle b){super.onCreate(b); token=getPreferences(0).getString("token",""); userId=getPreferences(0).getString("userId",""); if(token.isEmpty()) showAuth(); else dashboard();}
  TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setPadding(20,14,20,14);return t;}
  Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
  EditText input(String hint,boolean secret){EditText e=new EditText(this);e.setHint(hint);e.setPadding(20,12,20,12);if(secret)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);return e;}
  void base(String title){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);TextView h=tv("  "+title,22);h.setTextColor(Color.WHITE);h.setBackgroundColor(Color.rgb(7,94,84));root.addView(h,new LinearLayout.LayoutParams(-1,70));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
  void showAuth(){base("ZAP  •  Steve");content.addView(tv("Connexion sécurisée",23));content.addView(tv("Crée ton compte Zap avec ton numéro et un PIN. Le PIN sert uniquement à ta session Zap.",15));phone=input("Numéro de téléphone",false);name=input("Nom (création)",false);pin=input("PIN — 4 chiffres minimum",true);content.addView(phone);content.addView(name);content.addView(pin);Button create=btn("Créer mon compte");Button login=btn("Se connecter");content.addView(create);content.addView(login);status=tv("",14);content.addView(status);create.setOnClickListener(v->auth(false));login.setOnClickListener(v->auth(true));}
  void auth(boolean login){String p=phone.getText().toString(),n=name.getText().toString(),pi=pin.getText().toString();if(p.isEmpty()||pi.length()<4){status.setText("Numéro et PIN requis.");return;}try{JSONObject o=new JSONObject();o.put("phone",p);o.put("pin",pi);if(!login)o.put("name",n);request("POST",login?"/api/login":"/api/register",o,r->{try{if(login){saveSession(r);}else{runOnUiThread(()->status.setText("Compte créé. Connecte-toi maintenant."));}}catch(Exception e){showError(e);}});}catch(Exception e){showError(e);}}
  void saveSession(JSONObject r)throws Exception{token=r.getString("token");userId=r.getJSONObject("user").getString("id");getPreferences(0).edit().putString("token",token).putString("userId",userId).apply();runOnUiThread(this::dashboard);}
  void dashboard(){base("ZAP  •  Accueil");content.addView(tv("Demander une connexion uniquement à une personne qui peut l'autoriser elle-même.",16));target=input("Numéro de la personne",false);content.addView(target);Button ask=btn("📩 Demander l'accès");Button incoming=btn("🔔 Demandes reçues");Button outgoing=btn("📤 Mes demandes");Button con=btn("🔗 Connexions actives");Button logout=btn("Déconnexion");content.addView(ask);content.addView(incoming);content.addView(outgoing);content.addView(con);content.addView(logout);status=tv("",14);content.addView(status);ask.setOnClickListener(v->ask());incoming.setOnClickListener(v->incoming());outgoing.setOnClickListener(v->outgoing());con.setOnClickListener(v->connections());logout.setOnClickListener(v->logout());checkNotifications();}
  void ask(){try{JSONObject o=new JSONObject();o.put("targetPhone",target.getText().toString());request("POST","/api/requests",o,r->runOnUiThread(()->status.setText("Demande envoyée. La personne doit l'accepter.")));}catch(Exception e){showError(e);}}
  void incoming(){request("GET","/api/requests/incoming",null,r->runOnUiThread(()->{try{JSONArray a=r.getJSONArray("requests");if(a.length()==0){status.setText("Aucune demande en attente.");return;}for(int i=0;i<a.length();i++){JSONObject q=a.getJSONObject(i);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.addView(tv("Demande de "+q.optString("requesterName","utilisateur")+" ("+q.optString("requesterPhone")+")",16));Button yes=btn("Autoriser");Button no=btn("Refuser");row.addView(yes);row.addView(no);content.addView(row);String id=q.getString("id");yes.setOnClickListener(v->respond(id,"accept"));no.setOnClickListener(v->respond(id,"reject"));}}catch(Exception e){status.setText(e.toString());}}));}
  void respond(String id,String action){try{JSONObject o=new JSONObject();o.put("action",action);request("POST","/api/requests/"+id+"/respond",o,r->runOnUiThread(()->status.setText(action.equals("accept")?"Connexion autorisée.":"Demande refusée.")));}catch(Exception e){showError(e);}}
  void outgoing(){request("GET","/api/requests/outgoing",null,r->runOnUiThread(()->{try{JSONArray a=r.getJSONArray("requests");status.setText(a.length()+" demande(s) trouvée(s).");for(int i=0;i<a.length();i++){JSONObject q=a.getJSONObject(i);content.addView(tv(q.optString("targetName")+" • "+q.optString("status"),15));}}catch(Exception e){status.setText(e.toString());}}));}
  void connections(){request("GET","/api/connections",null,r->runOnUiThread(()->{try{JSONArray a=r.getJSONArray("connections");if(a.length()==0){status.setText("Aucune connexion active.");return;}for(int i=0;i<a.length();i++){JSONObject q=a.getJSONObject(i);Button b=btn("🔗 "+q.optString("otherName")+" — Révoquer");content.addView(b);b.setOnClickListener(v->revoke(q.optString("id")));}}catch(Exception e){status.setText(e.toString());}}));}
  void revoke(String id){request("POST","/api/connections/"+id+"/revoke",new JSONObject(),r->runOnUiThread(()->status.setText("Connexion révoquée.")));}
  void checkNotifications(){request("GET","/api/notifications",null,r->runOnUiThread(()->status.setText("Demandes en attente : "+r.optInt("pendingRequests"))));}
  void logout(){request("POST","/api/logout",new JSONObject(),r->{getPreferences(0).edit().clear().apply();token="";runOnUiThread(this::showAuth);});}
  void request(String method,String path,JSONObject body,JsonCallback cb){ex.execute(()->{HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(API+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(10000);c.setReadTimeout(10000);c.setRequestProperty("Accept","application/json");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes("UTF-8"));}}int code=c.getResponseCode();InputStream is=code>=400?c.getErrorStream():c.getInputStream();BufferedReader br=new BufferedReader(new InputStreamReader(is));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line);JSONObject r=new JSONObject(sb.toString());if(code>=400)throw new Exception(r.optString("error",r.toString()));cb.done(r);}catch(Exception e){showError(e);}finally{if(c!=null)c.disconnect();}});}
  interface JsonCallback{void done(JSONObject r);}
  void showError(Exception e){runOnUiThread(()->Toast.makeText(this,"Erreur : "+e.getMessage(),Toast.LENGTH_LONG).show());}
}
